In [7]:
import numpy as np
import pandas as pd

In [59]:
df = pd.read_csv("bitcoin_data.csv")
df

Date     Close
0     1/1/2022 0:00  46224.93
1     1/1/2022 0:01  46309.63
2     1/1/2022 0:02  46378.34
3     1/1/2022 0:03  46347.92
4     1/1/2022 0:04  46347.67
...             ...       ...
8635  7/1/2022 0:00  43142.26
8636  7/1/2022 0:01  43099.28
8637  7/1/2022 0:02  43135.15
8638  7/1/2022 0:03  43116.29
8639  7/1/2022 0:04  43113.05

[8640 rows x 2 columns]

In [61]:
df.drop(['Date'], 1, inplace=True)

<ipython-input-61-4ce20afa0cea>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df.drop(['Date'], 1, inplace=True)


In [62]:
df.rename(columns = {'Close':'Price'}, inplace=True)

In [63]:
df.head(7)

Price
0  46224.93
2  46378.34
3  46347.92
4  46347.67
5  46411.40
6  46485.51
7  46427.88

In [64]:
# A variable for predicting 'n' price in future
prediction_days=180 #n = prediction_days = 180
# Create another column shifted 'n' units up
df['Prediction'] = df[['Price']].shift(-prediction_days)

In [65]:
df.head(7)

Price  Prediction
0  46224.93    46813.08
2  46378.34    46804.80
3  46347.92    46768.31
4  46347.67    46791.36
5  46411.40    46781.73
6  46485.51    46800.67
7  46427.88    46807.49

In [66]:
df.tail(7)

Price  Prediction
8633  43147.33         NaN
8634  43103.33         NaN
8635  43142.26         NaN
8636  43099.28         NaN
8637  43135.15         NaN
8638  43116.29         NaN
8639  43113.05         NaN

In [67]:
# Convert the dataframe to a numpy array and drop the prediction column
X = np.array(df.drop(['Prediction'],1))

#Remove the last 'n' rows where 'n' is the prediction_days
X = X[:len(df)-prediction_days]

print(X)

[[46224.93]
 [46378.34]
 [46347.92]
 ...
 [43215.43]
 [43225.12]
 [43192.24]]


<ipython-input-67-a227313cd712>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = np.array(df.drop(['Prediction'],1))


In [68]:
# Create the dependent data set
# Convert the dataframe to a numpy array
y = np.array(df['Prediction'])
# Get all of the values except the last 'n' rows
y = y[:-prediction_days]
print(y)

[46813.08 46804.8  46768.31 ... 43135.15 43116.29 43113.05]


In [69]:
#Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [70]:
#Set the prediction_days_array equal to last 180 rows from the orignal data set
prediction_days_array = np.array(df.drop(['Prediction'], 1))[-prediction_days:]
print(prediction_days_array)

[[43238.96]
 [43195.47]
 [43162.31]
 [43174.38]
 [43139.11]
 [43156.96]
 [43177.59]
 [43204.62]
 [43185.31]
 [43159.09]
 [43156.97]
 [43160.67]
 [43188.64]
 [43200.94]
 [43202.6 ]
 [43224.25]
 [43212.19]
 [43208.97]
 [43213.78]
 [43193.81]
 [43134.  ]
 [43130.01]
 [43143.6 ]
 [43160.92]
 [43198.01]
 [43224.48]
 [43222.46]
 [43237.64]
 [43218.91]
 [43191.1 ]
 [43205.3 ]
 [43184.06]
 [43176.67]
 [43204.02]
 [43205.9 ]
 [43170.74]
 [43166.83]
 [43184.61]
 [43146.11]
 [43127.43]
 [43100.01]
 [43102.7 ]
 [43127.12]
 [43146.59]
 [43136.38]
 [43158.42]
 [43174.79]
 [43169.37]
 [43150.75]
 [43158.61]
 [43150.46]
 [43148.63]
 [43115.91]
 [43117.88]
 [43129.2 ]
 [43150.03]
 [43126.37]
 [43120.71]
 [43134.76]
 [43130.91]
 [43149.04]
 [43159.8 ]
 [43157.29]
 [43113.11]
 [43119.68]
 [43125.95]
 [43113.18]
 [43097.01]
 [43051.57]
 [43036.6 ]
 [43077.37]
 [43027.12]
 [43016.98]
 [43060.53]
 [43064.11]
 [43124.  ]
 [43145.86]
 [43122.66]
 [43118.12]
 [43157.16]
 [43148.2 ]
 [43157.34]
 [43136.24]
 [43

<ipython-input-70-43ba42c90ab5>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  prediction_days_array = np.array(df.drop(['Prediction'], 1))[-prediction_days:]


In [71]:
from sklearn.svm import SVR
#Create and train the Support Vector Machine (Regression) using radial basis function
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.00001)
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, gamma=1e-05)

In [72]:
#Test the Model
svr_rbf_confidence = svr_rbf.score(x_test, y_test)
print("svr_rbf accuracy: ", svr_rbf_confidence)

svr_rbf accuracy:  0.9151574640063829


In [73]:
#Print the predicted values
svm_prediction = svr_rbf.predict(x_test)
print(svm_prediction)

print()

#Print the actual values
print(y_test)

[46377.70736941 47162.79396852 46999.26767824 ... 47082.07699531
 43419.60387371 43172.9039223 ]

[46249.49 47253.96 47348.04 ... 46822.64 43465.88 43174.82]


In [58]:
#Print the model prediction for the next 'n=180' days
svm_prediction = svr_rbf.predict(prediction_days_array)
print(svm_prediction)

[46889.4970317  46847.3566203  46792.44825667 46955.63586886
 46949.30920134 46911.12002789 46895.48493657 46904.68440552
 46887.56047214 46792.50070719 46859.68742785 46905.77769947
 46917.88824602 46863.62826854 46845.66840832 46778.31971326
 46849.77051291 46816.98171896 46811.49291401 46745.28232387
 46743.89876911 46690.58182613 46670.94523945 46705.99722677
 46859.9606492  46840.48550627 46851.95288538 46829.71206342
 46860.45719446 46901.41533497 46935.72269896 47006.79488919
 46965.32072818 46961.99426262 46973.38900025 46989.89925955
 46989.91776174 46997.8348716  47020.60690917 47065.50065438
 47059.35649635 47053.24275975 47058.80774029 47053.14326513
 47040.10603382 46959.23080908 46975.15317804 46970.26643433
 46931.57167528 46918.65998476 46905.75445995 46961.60670178
 46968.03349146 46942.29389452 46897.11453942 46888.63704179
 46875.65422882 46843.06756763 46795.95937221 46854.58004261
 46812.21902627 46823.37538167 46782.59097366 46795.5928355
 46841.44819396 46848.589